// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX2yR9CejK7vwyytSTJR0EG1fO3LKw9vs',
    appId: '1:319866823641:web:efddef72616fdfcb106fc8',
    messagingSenderId: '319866823641',
    projectId: 'actionplanner-1f6f3',
    authDomain: 'actionplanner-1f6f3.firebaseapp.com',
    storageBucket: 'actionplanner-1f6f3.appspot.com',
    measurementId: 'G-HYB3EZ6VEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsv_gaiEgaD_TxOhg2OVNKpkTUn6blC28',
    appId: '1:319866823641:android:71692cb7a1015cb3106fc8',
    messagingSenderId: '319866823641',
    projectId: 'actionplanner-1f6f3',
    storageBucket: 'actionplanner-1f6f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHOa5TwnnycQV3lWycuQnHBVMJuPtfwbM',
    appId: '1:319866823641:ios:713b8705abafec92106fc8',
    messagingSenderId: '319866823641',
    projectId: 'actionplanner-1f6f3',
    storageBucket: 'actionplanner-1f6f3.appspot.com',
    iosClientId: '319866823641-3il4mmn5ddq8holeqn2jj02k839etemj.apps.googleusercontent.com',
    iosBundleId: 'com.example.actionPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHOa5TwnnycQV3lWycuQnHBVMJuPtfwbM',
    appId: '1:319866823641:ios:713b8705abafec92106fc8',
    messagingSenderId: '319866823641',
    projectId: 'actionplanner-1f6f3',
    storageBucket: 'actionplanner-1f6f3.appspot.com',
    iosClientId: '319866823641-3il4mmn5ddq8holeqn2jj02k839etemj.apps.googleusercontent.com',
    iosBundleId: 'com.example.actionPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX2yR9CejK7vwyytSTJR0EG1fO3LKw9vs',
    appId: '1:319866823641:web:4a0605684fbd8fd6106fc8',
    messagingSenderId: '319866823641',
    projectId: 'actionplanner-1f6f3',
    authDomain: 'actionplanner-1f6f3.firebaseapp.com',
    storageBucket: 'actionplanner-1f6f3.appspot.com',
    measurementId: 'G-CMTNFFDTQ1',
  );

}